# Generated by Django 3.1.3 on 2020-12-21 17:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('site_settings', '0003_auto_20201220_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', wagtail_color_panel.fields.ColorField(max_length=7)),
                ('color2', wagtail_color_panel.fields.ColorField(max_length=7)),
                ('color3', wagtail_color_panel.fields.ColorField(max_length=7)),
                ('color4', wagtail_color_panel.fields.ColorField(max_length=7)),
                ('color5', wagtail_color_panel.fields.ColorField(max_length=7)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Цветовая схема',
                'verbose_name_plural': 'Цветовая схема',
            },
        ),
    ]
